version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf" 
      - "./progect/static:/usr/share/nginx/html"
      - "./progect/gutendex/templates:/usr/share/nginx/html/gutendex/templates"
  
  app:
    container_name: app
    build: .
    # ports:
    #   - 8000:8000
    depends_on:
      post_db:
        condition: service_healthy


  post_db:
    container_name: post_db
    image:  postgres:14
    environment:  
       - POSTGRES_USER=gutendex
       - POSTGRES_PASSWORD=password
       - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - dvir:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U gutendex"]
      interval: 10s
      timeout: 5s
      retries: 5




networks:
  nginx-app:
  app-db:
    
volumes:
  dvir:
    


