version: '3'

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app
  #   volumes:
  #     - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf' 
  #     - "./flask-app:/app"
    
  # app:
  #   container_name: app
  #   build: ./flask-app
  #   depends_on:
  #     - post_db


  post_db:
    container_name: post_db
    image:  postgres:14
    environment:  
       - POSTGRES_USER=gutendex
       - POSTGRES_PASSWORD=password
       - PGDATA=/var/lib/postgresql/data/pgdata
      
    volumes:
      - dvir:/var/lib/postgresql/data




networks:
  nginx-app:
  app-db:
    
    
    


