version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf" 
      - "./gutendex/static:/usr/share/nginx/html/static"
    networks:
      - nginx-app
  
  app:
    container_name: app
    build: .
    depends_on:
      post_db:
        condition: service_healthy
    networks:
      - app-db
      - nginx-app


  post_db:
    container_name: post_db
    image:  postgres:14-alpine3.17
    environment:  
       - POSTGRES_USER=gutendex
       - POSTGRES_PASSWORD=password
       - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - dvir:/var/lib/postgresql/data
    networks:
      - app-db
    healthcheck:
      test: ["CMD-SHELL", "psql -U gutendex"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  nginx-app:
  app-db:
    
volumes:
  dvir:
    


